= 監査情報を記録する

[[anno_created_at]]
== 作成／更新日時の自動設定

レコードの挿入時、更新時に自動的にタイムスタンプを設定したい時があります。

その場合、フィールドにアノテーション ``@CreatedAt`` / ``@UpdatedAt`` を付与します。

* アノテーションを付与するには<<temporal_type,時制型>>である必要があります。
* ``@CreatedAt`` は、レコードの作成、すなわち、SQLの ``INSERT`` 文を実行するときにシステム日時を設定します。
* ``@UpdatedAt`` は、レコードの作成時と更新時、すなわち、SQLの ``INSERT / UPDATE`` 文を実行するときにシステム日時を設定します。 


NOTE: この機能は、SQL実行前にエンティティのフィールドの値を更新して実行します。
そのため、何かしらのエラーによりDBのロールバックがされたときは、更新されたエンティティのフィールドの値は戻らないので注意してください。

[source,java]
----
@Entity
public class User {

    @Id
    private long id;

    private String name;

    @CreatedAt
    private Timestamp createdAt;

    @UpdatedAt
    private Timestamp updatedAt;

    // getter/setterは省略
}
----

[[anno_created_by]]
== 作成／更新ユーザの永続化方法

レコードの挿入時、更新時に自動的に操作したユーザ情報を設定したい時があります。

その場合、フィールドにアノテーション ``@CreatedBy`` / ``@UpdatedBy`` を付与します。

* 本機能を利用するには、インタフェース ``AuditorProvider`` を実装したクラスをSpringBeanに登録する必要があります。
** Spring Securityを利用している場合は、``SecurityContextHolder`` からユーザ情報を取得します。
* ``@CreatedBy`` は、レコードの作成、すなわち、SQLの ``INSERT`` 文を実行するときにユーザ情報を設定します。
* ``@UpdatedBy`` は、レコードの作成時と更新時、すなわち、SQLの ``INSERT / UPDATE`` 文を実行するときにユーザ情報を設定します。

NOTE: この機能は、SQL実行前にエンティティのフィールドの値を更新して実行します。
そのため、何かしらのエラーによりDBのロールバックがされたときは、更新されたエンティティのフィールドの値は戻らないので注意してください。

.エンティティの定義
[source,java]
----
@Entity
public class User {

    @Id
    private long id;

    private String name;

    @CreatedAt
    private String createdBy;

    @UpdateddAt
    private String updatedBy;

    // getter/setterは省略
}
----

.ユーザ情報の取得の実装例
[source,java]
----
import java.util.Optional;

import com.github.mygreen.sqlmapper.core.audit.AuditorProvider;

import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

@Component
public class MyAuditorProvider<String> implements AuditorProvider {

    /**
     * 現在の監査人を取得します。
     *
     * @return 現在の監査人。
     */
    Optional<String> getCurrentAuditor() {
        Authentication authentication =
                SecurityContextHolder.getContext().getAuthentication();
        if (authentication == null || !authentication.isAuthenticated()) {
            // 未ログインのときのユーザ名
            return "unknown";
        }

        LoginUser user = (LoginUser) authentication.getPrincipal();
        return Optional.ofNullable(user.getName());
    }
}
----