[[setup_spring_boot]]
= Spring Bootの設定

Spring Boot のSqlMapper 専用の starter を使った環境設定方法を説明します。

== Mavenへのライブラリの依存関係の追加

Mavenを使用している場合は、``pom.xml`` に依存関係を追加します。

利用するDBのJDBCドライバの定義も追加します。

.pom.xmlへの依存関係の追加
[source, xml, subs="attributes+"]
----
<project>
    <dependencies>
		<!-- SQLMapperのSpringBoot用のstarterの追加 -->
        <dependency>
			<groupId>com.github.mygreen.sqlmapper</groupId>
			<artifactId>sqlmapper-spring-boot-starter</artifactId>
			<version>{app-ver}</version>
		</dependency>

		<!-- 利用するDBのJDBCドライバを追加します -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
		</dependency>

    </dependencies>
</project>
----

さらに、メタモデルを自動生成する設定を追加します。

.pom.xmlへのメタモデルの自動生成設定の追加
[source, xml, subs="attributes+"]
----
<project>
    <build>
        <plugins>
            <!-- メタモデルを生成するプラグインを追加します -->
            <plugin>
				<groupId>com.mysema.maven</groupId>
				<artifactId>apt-maven-plugin</artifactId>
				<version>1.1.3</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>process</goal>
						</goals>
						<configuration>
							<outputDirectory>target/generated-sources/java</outputDirectory>
							<logOnlyOnError>false</logOnlyOnError>
							<processors>
								<processor>com.github.mygreen.sqlmapper.apt.EntityMetamodelProcessor</processor>
							</processors>
							<sourceEncoding>UTF-8</sourceEncoding>
						</configuration>
					</execution>
				</executions>
                <dependencies>
				    <dependency>
						<groupId>com.github.mygreen.sqlmapper</groupId>
						<artifactId>sqlmapper-apt</artifactId>
						<version>{app-ver}</version>
					</dependency>
			    </dependencies>
			</plugin>
        </plugins>
    </build>
</project>
----

== Gradleへのライブラリの依存関係の追加

Gradleを使用している場合は、``build.gradle`` に依存関係を追加します。

利用するDBのJDBCドライバの定義も追加します。

さらに、メタモデルを自動生成する設定を追加します。

.build.gradleへの依存関係の追加
[source, groovy, subs="attributes+"]
----
dependencies {
	implementation 'com.github.mygreen.sqlmapper:sqlmapper-spring-boot-starter:{app-ver}'

	// 利用するDBのJDBCドライバを追加
	implementation 'com.h2database:h2:2.1.210'

	// メタモデルを自動生成する設定
	annotationProcessor 'com.github.mygreen.sqlmapper:sqlmapper-apt:{app-ver}'
}
----

== データソースの設定

データソースの接続定義をアプリケーションプロパティに定義します。

* データソースの定義は、 https://spring.pleiades.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data[Spring Boot標準のプロパティ] を使用します。
** プロパティ `spring.datasource.XXX` を使用して定義します。
* 読み込まれたJDBCドライバの定義によって、<<db_dialect,DBの方言種別設定>> が自動的に読み込まれます。
** 判定は、Spring Bootの https://spring.pleiades.io/spring-boot/docs/current/api/org/springframework/boot/jdbc/DatabaseDriver.html[DatabaseDriver, role="externalink", window="_blank"] を使用して判定を行っているため、DatabaseDriverクラスが対応していないDBの場合は、 https://mygreen.github.io/sqlmapper/apidocs/com/github/mygreen/sqlmapper/core/dialect/Dialect.html[Dialect, role="externalink", window="_blank"] のSpring Beanを独自に定義して登録する必要があります。

.データソースの定義
[source,yaml]
----
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password: 
----

[[jdbc_driver]]
.DBのJDBCドライバー
|===
| DB種別| ドライバークラス | ライブラリ

| https://www.h2database.com[H2 Database Engine, role="externalink", window="_blank"]
|`org.h2.Driver`
|https://mvnrepository.com/artifact/com.h2database/h2[com.h2database:h2, role="externalink", window="_blank"]

| https://www.h2database.com/html/main.html[HSQLDB, role="externalink", window="_blank"]
|`org.hsqldb.jdbc.JDBCDriver`
|https://mvnrepository.com/artifact/org.hsqldb/hsqldb[org.hsqldb:hsqldb, role="externalink", window="_blank"]

| https://www.postgresql.jp/[PostgreSQL, role="externalink", window="_blank"]
|`org.postgresql.Driver`
|https://mvnrepository.com/artifact/org.postgresql/postgresql[org.postgresql:postgresql, role="externalink", window="_blank"]

| https://www.sqlite.org/[SQLite, role="externalink", window="_blank"]
|`org.sqlite.JDBC`
|https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc[org.xerial:sqlite-jdbc, role="externalink", window="_blank"]

.2+| https://www.oracle.com/jp/database/[Oracleデータベース, role="externalink", window="_blank"]
|`oracle.jdbc.OracleDriver`
|https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc11[com.oracle.database.jdbc:ojdbc11, role="externalink", window="_blank"]

|===

[[spring_boot_properties]]
=== プロパティの上書き

テーブルによる識別子の生成などの設定を上書きする場合は、SpringBootの ``applicaiton.yml`` や ``application.properties`` に定義します。

設定可能なプロパティは、<<available_properties,設定可能なプロパティ>> を参照してください。

=== DBコネクションプールの設定

* DBコネクションプールを使用する場合、 https://spring.pleiades.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data[Spring Boot標準のプロパティ, role="externalink", window="_blank"] を使用します。
** プロパティ `spring.datasource.XXX` を使用して定義します。
* https://commons.apache.org/proper/commons-dbcp/[Commons DBCP2, role="externalink", window="_blank"] / https://github.com/brettwooldridge/HikariCP[HikariCP, role="externalink", window="_blank"] など好きなものを使用してください。


.DBコネクションプールのデータソースの定義
[source,yaml]
----
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sampledb
    username: sample_user
    password: sample_password
	# DBコネクションプールのタイプを指定
	type: com.zaxxer.hikari.HikariDataSource
	# 各コネクションプールの設定値を指定
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
----