= Spring Framework の設定

非Spring Boot の環境、または、SqlMapperのstater を使用しない時の環境設定方法を説明します。

== Mavenへのライブラリの依存関係の追加

Mavenを使用している場合は、``pom.xml`` に依存関係を追加します。

利用するDBのJDBCドライバの定義も追加します。

.pom.xmlへの依存関係の追加
[source, xml, subs="attributes+"]
----
<project>
    <dependencies>
		<!-- SQLMapperの定義 -->
		<dependency>
			<groupId>com.github.mygreen.sqlmapper</groupId>
			<artifactId>sqlmapper-core</artifactId>
			<version>{app-ver}</version>
		</dependency>

		<!-- 利用するDBのJDBCドライバを追加します -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>2.1.210</version>
		</dependency>

    </dependencies>
</project>
----

さらに、メタモデルを自動生成する設定を追加します。

.pom.xmlへのメタモデルの自動生成設定の追加
[source, xml, subs="attributes+"]
----
<project>
    <build>
        <plugins>
            <!-- メタモデルを生成するプラグインを追加します -->
            <plugin>
				<groupId>com.mysema.maven</groupId>
				<artifactId>apt-maven-plugin</artifactId>
				<version>1.1.3</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>process</goal>
						</goals>
						<configuration>
							<outputDirectory>target/generated-sources/java</outputDirectory>
							<logOnlyOnError>false</logOnlyOnError>
							<processors>
								<processor>com.github.mygreen.sqlmapper.apt.EntityMetamodelProcessor</processor>
							</processors>
							<sourceEncoding>UTF-8</sourceEncoding>
						</configuration>
					</execution>
				</executions>
                <dependencies>
				    <dependency>
						<groupId>com.github.mygreen.sqlmapper</groupId>
						<artifactId>sqlmapper-apt</artifactId>
						<version>{app-ver}</version>
					</dependency>
			    </dependencies>
			</plugin>
        </plugins>
    </build>
</project>
----

== Gradleへのライブラリの依存関係の追加

Gradleを使用している場合は、``build.gradle`` に依存関係を追加します。

利用するDBのJDBCドライバの定義も追加します。

さらに、メタモデルを自動生成する設定を追加します。

.build.gradleへの依存関係の追加
[source, groovy, subs="attributes+"]
----
dependencies {
	implementation 'com.github.mygreen.sqlmapper:sqlmapper-spring-boot-starter:{app-ver}'

	// 利用するDBのJDBCドライバを追加
	implementation 'com.h2database:h2:2.1.210'

	// メタモデルを自動生成する設定
	annotationProcessor 'com.github.mygreen.sqlmapper:sqlmapper-apt:{app-ver}'

}
----

[[spring_normal_java_config]]
== JavaConfigの設定

SqlMapper用のJavaConfigのサポートクラス ``SqlMapperConfigurationSupport`` を継承して定義します。

データソースとDBの方言種別を環境に合わせ定義します。DBの方言の詳細については https://mygreen.github.io/sqlmapper/apidocs/com/github/mygreen/sqlmapper/core/dialect/package-summary.html[JavaDoc, role="externalink", window="_blank"] を参照してください。

.JavaConfigの定義
[source, java]
----
import javax.sql.DataSource;

import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import com.github.mygreen.sqlmapper.core.config.SqlMapperConfigurationSupport;
import com.github.mygreen.sqlmapper.core.dialect.Dialect;
import com.github.mygreen.sqlmapper.core.dialect.H2Dialect;


@Configuration
public class SqlMapperConfig extends SqlMapperConfigurationSupport {

    // データソースの定義
    @Override
    public DataSource dataSource() {
        return new EmbeddedDatabaseBuilder()
                .generateUniqueName(true)
                .setType(EmbeddedDatabaseType.H2)
                .setScriptEncoding("UTF-8")
                .build();
    }

    // DBの方言種別の定義
    @Override
    public Dialect dialect() {
        return new H2Dialect();
    }
}
----

[[db_dialect]]
.DBの方言種別
|===
| DB種別| クラス | 説明

| https://www.h2database.com[H2 Database Engine, role="externalink", window="_blank"]
|`H2Dialect`
|Java製の組み込みDB。

| https://www.h2database.com/html/main.html[HSQLDB, role="externalink", window="_blank"]
|`HsqlDialect`
|Java製の組み込みDB。

| https://www.postgresql.jp/[PostgreSQL, role="externalink", window="_blank"]
|`PostgresDialect`
|OSSのRDMBS。

| https://www.sqlite.org/[SQLite, role="externalink", window="_blank"]
|`SqliteDialect`
|組み込みDB。

.2+| https://www.oracle.com/jp/database/[Oracleデータベース, role="externalink", window="_blank"]
|`OracleDialect`
|商用のRDBS。Oracle12c以上の場合に対応。
|`OracleLegacyDialect`
|Oracle11g以前に対応。

|===


[[spring_normal_properties]]
=== プロパティの上書き

テーブルによる識別子の生成などの設定を上書きする場合は、Springのアノテーション ``@PropertySource`` を使用し、プロパティを上書きします。

設定可能なプロパティは、<<available_properties,設定可能なプロパティ>> を参照してください。

.JavaConfigの定義
[source, java]
----
import org.springframework.context.annotation.PropertySource;

@Configuration
@PropertySource("classpath:application.properties")
public class SqlMapperConfig extends SqlMapperConfigurationSupport {
    // ・・・省略
}
----

=== DBコネクションプールの設定

DBコネクションプールを使用する場合、JavaConfigのDataSourceのインスタンスを変更します。

* https://commons.apache.org/proper/commons-dbcp/[Commons DBCP2] / https://github.com/brettwooldridge/HikariCP[HikariCP] など好きなものを使用してください。
* 設定値は `application.properties` などに定義しておき、 https://spring.pleiades.io/spring-framework/docs/current/javadoc-api/org/springframework/core/env/Environment.html[Environment, role="externalink", window="_blank"] で参照します。
** SqlMapperConfigurationSupportのプロパティ `env` で定義されてるため、JavaConfig内から参照できます。

.DBコネクションプールの設定例
[source, java]
----
import javax.sql.DataSource;

import org.apache.commons.dbcp2.BasicDataSource;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.github.mygreen.sqlmapper.core.config.SqlMapperConfigurationSupport;


@Configuration
@PropertySource("classpath:application.properties")
public class SqlMapperConfig extends SqlMapperConfigurationSupport {

    // データソースの定義
	@Bean(destroyMethod = "close")
    @Override
    public DataSource dataSource() {
		BasicDataSource dataSource = new BasicDataSource();
		dataSource.setDriverClassName(env.getRequiredProperty("jdbc.driverClassName"));
		dataSource.setUrl(env.getRequiredProperty("jdbc.url"));
		dataSource.setUsername(env.getRequiredProperty("jdbc.username"));
		dataSource.setPassword(env.getRequiredProperty("jdbc.password"));

		return dataSource();
    }

    // ・・・
}
----

.DB接続関連のプロパティ定義例
[source, properties]
----
jdbc.driverClassName=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost:5432/sampledb
jdbc.username=sample_user
jdbc.password=sample_password
----
