= 挿入

== 1件挿入

エンティティを挿入する場合は、`insert(...)` と `execute()` を組み合わせて使用します。

* `insert(...)` の引数はエンティティのインスタンスを指定します。
* `execute()` の戻り値は、更新した行数です。
* 挿入するときに識別子を自動設定できます。
** 詳細は、<<anno_generated_id,識別子の自動採番>> を参照してください。
* 一意制約違反によりエンティティの挿入ができない場合は、例外 `org.springframework.dao.DuplicateKeyException` がスローされます。

[source,java]
----
int count = sqlMapper.insert(employee)
        .execute();
----

== バッチ挿入

複数のエンティティをバッチ挿入する場合は、`insertBatch(...)` と `execute()` を組み合わせて使用します。

* `insertBatch(...)` の引数はエンティティのインスタンスのリストあるいは配列（可変長引数）を指定します。
* `execute()` の戻り値は、更新した行数の配列です。
* 挿入するときに識別子を自動設定できます。
** 詳細は、<<anno_generated_id,識別子の自動採番>> を参照してください。
* 一意制約違反によりエンティティの挿入ができない場合は、例外 `org.springframework.dao.DuplicateKeyException` がスローされます。

[source,java]
----
int[] countArray = sqlMapper.insertBatch(employees)
        .execute();
----

NOTE: 処理時のバッチサイズは引数で指定したエンティティのサイズと同一になります。
バッチサイズを変更したい場合は、エンティティを分割して実行してください。

== 指定したプロパティのみを挿入対象にする

* 指定したプロパティのみを挿入対象にする場合は、 `includes()` を使用します。
* 次のプロパティは自動的に挿入対象となり、`includes()` で指定する必要はありません。
** `@Id` を付与したID(主キー)。
** `@Version` を付与したバージョンキー（排他キー）。

[source,java]
----
MEmployee e = MEmployee.employee;

int count = sqlMapper.insert(employee)
        .includes(e.id, e.name)
        .execute();
----


NOTE: `includes(...)` と `excludes(...)` の両方で同じプロパティを指定した場合、`includes(...)` が優先されます。


== 指定したプロパティを挿入対象から除外する

* 指定したプロパティを挿入対象から除外する場合は、 `excludes()` を使用します。
* 次のプロパティは自動的に挿入対象となり、除外対象に指定できません。
** `@Id` を付与したID(主キー)。
** `@Version` を付与したバージョンキー（排他キー）。

[source,java]
----
MEmployee e = MEmployee.employee;

int count = sqlMapper.insert(employee)
        .excludes(e.version)
        .execute();
----

