= 検索

== 複数件検索

SQLファイルを使って、複数件検索をする場合は、`selectBySqlFile(..)` と `getResultList()` を組み合わせます。

[source,java]
----
SqlTemplateContext templateContext = new MapSqlTemplateContext(
        Map.of("salary", new BigDecimal(2000)));

List<Employee> results = sqlMapper.selectBySqlFile(
            Employee.class, 
            "examples/sql/employee/selectAll.sql", 
            templateContext)
        .getResultList();
----


== 1件検索

SQLファイルを使って1件検索をする場合は、 `selectBySqlFile(...)` と `getSingleResult()` を組み合わせます。

* 1件も見つからないときは、Springの例外 `EmptyResultDataAccessException` がスローされます。
* 2件以上見つかった場合、Springの例外 `IncorrectResultSizeDataAccessException` がスローされます。

[source,java]
----
SqlTemplateContext templateContext = new MapSqlTemplateContext(
        Map.of("id", 10));

Employee result = sqlMapper.sqlMapper.selectBySqlFile(
            Employee.class, 
            "examples/sql/employee/selectSingle.sql", 
            templateContext)
        .getSingleResult();
----

1件も見つからなかったときに例外をスローされないようにするには、`getOptionalResult()` を使用します。

* 戻り値を `java.util.Optinal` で受け取ることができます。
* ただし、2件以上見つかったときは Springの例外 `IncorrectResultSizeDataAccessException` がスローされます。
** 例外がスローされないようにするためにメソッド `limit(1)` による件数を指定することをお勧めします。

[source,java]
----
SqlTemplateContext templateContext = new MapSqlTemplateContext(
        Map.of("id", 10));

Optional<Employee> result =sqlMapper.sqlMapper.selectBySqlFile(
            Employee.class, 
            "examples/sql/employee/selectSingle.sql", 
            templateContext)
        .getOptionalResult();
----

== Streamによる検索

検索結果を多くの行を返しメモリの消費量が多く`List` でまとめて受け取ることが困難な場合は、フェッチによる参照として `getResultStream()` を使用します。

* Streamは、必ずクローズするようにしてください。

.Streamによるフェッチ検索
[source,java]
----
SqlTemplateContext templateContext = new MapSqlTemplateContext(
        Map.of("salary", new BigDecimal(2000)));

Stream<Employee> stream = sqlMapper.selectBySqlFile(
            Employee.class, 
            "examples/sql/employee/selectAll.sql", 
            templateContext)
        .getResultStream();

// try-with-resourceでStreamをクローズする。
try (stream) {
    stream.forEarch(entity -> {
        // 任意の処理
    });
}
----

== 検索結果の行数取得

`SELECT COUNT(*) ～` による検索結果の行数を取得するには、`getCountBySqlFile(...)` を使用します。

NOTE: SQLファイルで定義したSQLを、`select count(*) from (<SQLテンプレートの内容>)` に変換して実行されるため、`count` 句をSQLテンプレートに記載する必要はありません。

[source,java]
----
SqlTemplateContext templateContext = new MapSqlTemplateContext(
        Map.of("salary", new BigDecimal(2000)));

long count = sqlMapper.selectBySqlFile(
            Employee.class, 
            "examples/sql/employee/selectAll.sql", 
            templateContext)
            getCount();
----


== ページング

ページングを指定するには、以下のメソッドを使用します。

* `offset(int offset)` : 最初に取得する行の位置を指定します。最初の行の位置は0になります。 
* `limit(int limit)` : 取得する行数を指定します。

[NOTE]
====
 * SQLファイルで定義したSQLを、`<SQLテンプレートの内容> offset <開始位置> limit <取得行数>` に変換して実行されるため、`offset`/`limit` 句をSQLテンプレートに記載する必要はありません。
 * 並び順が一定になるように、SQLテンプレート内で並び順を指定しておく必要があります。
====


[source,java]
----
SqlTemplateContext templateContext = new MapSqlTemplateContext(
        Map.of("salary", new BigDecimal(2000)));

List<Employee> results = sqlMapper.selectBySqlFile(
            Employee.class, 
            "examples/sql/employee/selectAll.sql", 
            templateContext)
        .offset(10)
        .limit(100)
        .getResultList();
----


