-- 全てのテーブルのデータをリセットする

-- テーブルデータの削除
TRUNCATE table employee;
TRUNCATE table section;
TRUNCATE table business_establishment;
TRUNCATE table customer;
TRUNCATE table SAMPLE_IDENTITY2;
TRUNCATE table SAMPLE_SEQUENCE1;
TRUNCATE table SAMPLE_TABLE_ID1;
TRUNCATE table ID_SEQUENCE;

-- IDのリセット : ALTER TABLE <table_name> ALTER COLUMN <column_name> RESTART WITH 1
ALTER TABLE employee ALTER COLUMN id RESTART WITH 1;
ALTER TABLE SAMPLE_IDENTITY2 ALTER COLUMN id1 RESTART WITH 1;
ALTER TABLE SAMPLE_IDENTITY2 ALTER COLUMN id2 RESTART WITH 1;

-- シーケンスのリセット : ALTER SEQUENCE <sequence_name> RESTART WITH 1;
ALTER SEQUENCE SAMPLE_SEQUENCE1_ID RESTART WITH 1;

