= メタモデルとは

エンティティのメタモデルとは、Criteria API を使ってクエリを組み立てる際の補助的なクラスです。

次のようなエンティティクラスが定義されているとします。

.エンティティのコード
[source,java]
----
@Entity
public class Employee {

    @Id
    public Integer id;

    public String name;

    public Integer age;

    @Version
    public Integer version;
}
----

上記のエンティティクラスに対するメタモデルクラスは、`MEmployee` のコードになります。

エンティティクラスと同じ名前のプロパティ `id` / `name` / `age` / `vesion` を持ちます。

.メタモデルのコード
[source,java]
----
public class MEmployee extends EntityPathBase<Employee> {

    public static final MEmployee employee = new MEmployee("employee");

    public MEmployee(Class<? extends Employee> type, String name) {
        super(type, name);
    }

    public MEmployee(String name) {
        super(Employee.class, name);
    }

    public final StringPath id = createString("id");

    public final StringPath name = createString("name");

    public final NumberPath<Integer> age = createNumber("age", Integer.class);

    public final NumberPath<Long> version = createNumber("version", Long.class);
}
----

Criteria APIを使用して検索を行うとき、メタモデルクラスは検索条件を組み立てるときに使用できます。

プロパティのクラスタイプによって、予めSQLの演算子に対応するメソッドが実装されており、迷うことなくクエリを組み立てることができます。

.Criteria APIの検索条件の組み立て
[source,java]
----
MEmployee e = MEmployee.employee;

List<Employee> results = sqlMapper.selectFrom(e)
        .where(e.name.lower().starts("yamada").and(e.age.beteween(20, 30)))
        .getResultList();
----

組み立てられるSQLは次のようになります。

[source,sql]
----
select T1_.ID, T1_.NAME, T1_.AGE, T1_.VERSION  from EMPLOYEE T1_ where lower(T1_.NAME) like ? and T1.AGE BETWEEN ? and ? 
----

* メタモデルを使用すると、演算子に対するメソッドの引数として、ジェネリクスを使用しているため、ある程度 *型安全（タイプセーフ* に利用できます。
** 例えば、String型のプロパティ `name` に対するメソッド `starts(...)` は、文字列型を渡す必要がありますが、数値型を渡すとコンパイルエラーとなります。
* また、メタモデルの他の利点として、テーブルのカラムを変更する際、エンティティのプロパティの名称も変更しますが、Criteria APIで使用している個所がコンパイルエラーとなり、 *影響個所* がすぐにわかります。さらに、プロパティ名の綴り間違など防ぐことができます。

NOTE: 本ライブラリのCriteria APIの型安全は、プロパティのクラスタイプしか保障しません。
例えば、同じ文字列型であるが電話番号と氏名は別な意味であり、ドメインという意味的な範囲は保障できません。
