# 更新

## 1件挿入

エンティティを更新する場合は、`update(...)` と `execute()` を組み合わせます。

* `update(...)` の引数はエンティティのインスタンスを指定します。
* `execute()` の戻り値は、更新した行数です。
** 更新対象のプロパティ（カラム）がない場合は、`0` を返します。
* 更新するときに、バージョンによる楽観的排他制御をすることができます。
** 楽観敵排他エラーが発生したときは例外 `org.springframework.dao.OptimisticLockingFailureException` がスローされます。。 
** 詳しくは、 <<anno_version, バージョン定義>> を参照してください。
* 識別子定義のなエンティティは `update(...)` で更新することはできません。

[source,java]
----
int count = sqlMapper.update(employee)
        .execute();
----

## バッチ更新

複数のエンティティをバッチ更新する場合は、`updateBatch(...)` と `execute()`` を組み合わせます。

* `updateBatch(...)` の引数はエンティティのインスタンスのリストあるいは配列（可変長引数）を指定します。
* `execute()` の戻り値は、更新した行数の配列です。
* 更新するときに、バージョンによる楽観的排他制御をすることができます。
** 楽観敵排他エラーが発生したときは例外 `org.springframework.dao.
** 詳しくは、 <<anno_version, バージョン定義>> を参照してください。
* 識別子定義のなエンティティは `updateBatch(...)` で更新することはできません。

[source,java]
----
int[] countArray = sqlMapper.updateBatch(employees)
        .execute();
----

NOTE: 処理時のバッチサイズは引数で指定したエンティティのサイズと同一になります。
バッチサイズを変更したい場合は、エンティティを分割して実行してください。

## バージョンプロパティを通常の更新対象にする

バージョンプロパティを通常の更新対象に含め、バージョンチェックの対象外にする場合は、  `includesVersion()` を使います。

[source,java]
----
int count = sqlMapper.update(employee)
        .includesVersion()
        .execute();
----

## nullの項目を更新しない

更新の対象からnullの項目を除外する場合は、 `excludesNull()` を使用します。 

NOTE: バッチ系の更新は、すべてのエンティティに同じSQLを適用しなければならないので、 null を除外してバッチ更新することはできません。
なぜなら、すべてのエンティティの null の項目が同じだとは限らないからです。

[source,java]
----
int count = sqlMapper.update(employee)
        .excludesNull()
        .execute();
----

## 指定したプロパティのみを更新対象にする

指定したプロパティのみを更新対象にする場合は、`includes()` を使用します。

[source,java]
----
MEmployee e = MEmployee.employee;

int count = sqlMapper.update(employee)
        .includes(e.id, e.name)
        .execute();
----


## 指定したプロパティを更新対象から除外する

指定したプロパティを更新対象から除外する場合は、 `excludes()` を使用します。

[source,java]
----
MEmployee e = MEmployee.employee;

int count = sqlMapper.update(employee)
        .excludes(e.version)
        .execute();
----

## 変更のあったプロパティのみを更新対象にする

変更のあったプロパティのみを更新対象にする場合は、`changedFrom()` を使います。

NOTE: バッチ系の更新は、すべてのエンティティに同じSQLを適用しなければならないので、 変更のあったプロパティのみをバッチ更新することはできません。
なぜなら、変更のあったプロパティがすべてのエンティティで同じだとは限らないからです。
最初の引数は、変更前の状態を持ったエンティティもしくはマップです。

[source,java]
----
Employee before = ...;

int count = sqlMapper.update(employee)
        .changedFrom(before)
        .execute();
----

## 更新行数をチェックしない

バージョンによる楽観的排他制御を行う場合、 更新できた行数が0だと `org.springframework.dao.OptimisticLockingFailureException` が発生します。

更新行数を正しく返さないJDBCドライバを使用する場合は、`suppresOptimisticLockException()` を呼び出すことで、更新できた行数のチェックを行わなくなります。


[source,java]
----
Employee before = ...;

int count = sqlMapper.update(employee)
        .suppresOptimisticLockException()
        .execute();
----

